# Generated by Django 4.2.1 on 2023-07-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temmuz15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='temmuz15gecesi/static/img/')),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Time', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
