# Generated by Django 4.2.1 on 2023-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('subTitle', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='./static/img/')),
            ],
        ),
    ]
