# Generated by Django 4.2.1 on 2023-07-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='Link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
