# Generated by Django 4.2.1 on 2023-06-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bagis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baslik', models.CharField(blank=True, max_length=200, null=True)),
                ('Tutar', models.IntegerField(blank=True, null=True)),
                ('Aciklama', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
