# Generated by Django 4.2.1 on 2023-06-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagis',
            name='Bagis_Resim',
            field=models.ImageField(blank=True, null=True, upload_to='donations/static/img'),
        ),
    ]
