# Generated by Django 4.2.1 on 2023-06-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_bagis_bagis_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagis',
            name='Bagis_Resim',
            field=models.ImageField(blank=True, null=True, upload_to='djangouploads/donations/images'),
        ),
    ]
