# Generated by Django 4.2.1 on 2023-06-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iller',
            fields=[
                ('Sehir', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
