# Generated by Django 4.2.1 on 2023-06-25 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teskilat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Iller',
        ),
    ]
