# Generated by Django 4.2.1 on 2023-07-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teskilat', '0002_delete_iller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Il',
            fields=[
                ('Sehir_Ismi', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('Sehir_Plaka_Kodu', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
