# Generated by Django 4.2.1 on 2023-07-06 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teskilat', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ilce_Ismi', models.CharField(max_length=100)),
                ('Ilce_Sehir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teskilat.il')),
            ],
        ),
    ]
