# Generated by Django 4.2.1 on 2023-07-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teskilat', '0004_ilce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teskilat.il')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teskilat.ilce')),
            ],
        ),
    ]
