# Generated by Django 4.2.1 on 2023-07-06 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teskilat', '0005_deneme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Il_Baskanligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yonetici_Ismi', models.CharField(blank=True, max_length=200, null=True)),
                ('Yonetici_Sifati', models.CharField(blank=True, max_length=200, null=True)),
                ('Yonetici_Biyografisi', models.TextField(blank=True, null=True)),
                ('Yonetici_Resmi', models.ImageField(upload_to='djangouploads/teskilat/il_baskanligi/')),
                ('Yonetici_Durumu', models.CharField(blank=True, choices=[('Baskan', 'Baskan'), ('Diger', 'Diger')], default='Diger', max_length=50, null=True)),
                ('Yonetici_Il', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teskilat.il')),
            ],
        ),
        migrations.CreateModel(
            name='Ilce_Baskanligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yonetici_Ismi', models.CharField(blank=True, max_length=200, null=True)),
                ('Yonetici_Sifati', models.CharField(blank=True, max_length=200, null=True)),
                ('Yonetici_Biyografisi', models.TextField(blank=True, null=True)),
                ('Yonetici_Resmi', models.ImageField(upload_to='djangouploads/teskilat/ilce_baskanligi/')),
                ('Yonetici_Durumu', models.CharField(blank=True, choices=[('Baskan', 'Baskan'), ('Diger', 'Diger')], default='Diger', max_length=50, null=True)),
                ('Yonetici_Il', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teskilat.ilce')),
            ],
        ),
        migrations.DeleteModel(
            name='Deneme',
        ),
    ]
