# Generated by Django 4.2.1 on 2023-06-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurumsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Federasyon_Aciklama_Title', models.CharField(max_length=200)),
                ('Federasyon_Aciklama_Text', models.TextField()),
                ('Federasyon_Misyon_Title', models.CharField(max_length=200)),
                ('Federasyon_Misyon_Text', models.TextField()),
                ('Federasyon_Vizyon_Title', models.CharField(max_length=200)),
                ('Federasyon_Vizyon_Text', models.TextField()),
            ],
        ),
    ]
