# Generated by Django 4.2.1 on 2023-06-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel_baskanlik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denetim_kurulu',
            name='Yonetici_Resmi',
            field=models.ImageField(blank=True, null=True, upload_to='djangouploads/genel_baskanlik/images/'),
        ),
        migrations.AlterField(
            model_name='disiplin_kurulu',
            name='Yonetici_Resmi',
            field=models.ImageField(blank=True, null=True, upload_to='djangouploads/genel_baskanlik/images/'),
        ),
        migrations.AlterField(
            model_name='yonetim_kurulu',
            name='Yonetici_Resmi',
            field=models.ImageField(blank=True, null=True, upload_to='djangouploads/genel_baskanlik/images/'),
        ),
        migrations.AlterField(
            model_name='yurutme_kurulu',
            name='Yonetici_Resmi',
            field=models.ImageField(blank=True, null=True, upload_to='djangouploads/genel_baskanlik/images/'),
        ),
    ]
