# Generated by Django 4.2.1 on 2023-07-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel_baskanlik', '0002_alter_denetim_kurulu_yonetici_resmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denetim_kurulu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disiplin_kurulu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yonetim_kurulu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yurutme_kurulu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
