# Generated by Django 4.2.1 on 2023-06-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehitler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sehit',
            name='Sehit_Biyografi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sehit',
            name='Sehit_Dogum_Yili',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
