# Generated by Django 4.1.4 on 2023-06-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sehitler", "0002_sehit_sehit_biyografi_sehit_sehit_dogum_yili"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sehit",
            name="Sehit_Resmi",
            field=models.ImageField(
                blank=True, null=True, upload_to="djangouploads/sehitler/images"
            ),
        ),
    ]
